### ISSUE TITLE
Glext issue while compiling.

### ISSUE THREAD

**Issue by ealione** [ericjang/glsl-playground#1]
Trying to compile using Qt5.5 on Windows I get 

glwidget.cpp:5: error: C1083: Cannot open include file: 'GL/glext.h': No such file or directory

**Comment by ealione** [comment]
By the way including the file on your own throws out about 128 errors. Was this software actually made for older Qt versions?
